version: ">= 0.14.0"

formatter: markdown table

content: |-
  # Terraform ACI System Performance Module

  Manage ACI Global System Performance settings

  Location in GUI:
  'System' » 'System Settings' » 'System Performance'

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
