version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Firmware Group Module

  Manages ACI Firmware Group

  Location in GUI:
  `Admin` » `Firmware` » `Nodes`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
