version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Inband Endpoint Group Module

  Manages ACI Inband Endpoint Group

  Location in GUI:
  `Tenants` » `mgmt` » `Node Management EPGs`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
