version: ">= 0.14.0"

formatter: markdown table

content: |-
  # Terraform ACI Route Tag Policy Module

  Description

  Location in GUI:
  `Tenants` » `Policies` » `Protocol` » `Route Tag`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
