version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Service Graph Template Module

  Manages ACI Service Graph Template

  Location in GUI:
  `Tenants` » `XXX` » `Services` » `L4-L7` » `Service Graph Templates`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
