version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Physical Domain Module

  Manages ACI Physical Domain

  Location in GUI:
  `Fabric` » `Access Policies` » `Physical and External Domains` » `Physical Domains`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
