version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Config Export Module

  Manages ACI Config Export

  Location in GUI:
  `Admin` » `Import/Export` » `Export Policies` » `Configuration`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
