version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Spanning Tree Policy Module

  Manages ACI Spanning Tree Policy

  Location in GUI:
  `Fabric` » `Access Policies` » `Policies` » `Interface` » `Spanning Tree Interface`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
