version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Fabric Pod Profile Module

  Manages ACI Fabric Pod Profile

  Location in GUI:
  `Fabric` » `Fabric Policies` » `Pods` » `Profiles`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
