version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Node Registration Module

  Manages ACI Node Registration

  Location in GUI:
  `Fabric` » `Inventory` » `Fabric Membership`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
