version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Fabric Leaf Switch Policy Group Module

  Manages ACI Fabric Leaf Switch Policy Group

  Location in GUI:
  `Fabric` » `Fabric Policies` » `Switches` » `Leaf Switches` » `Policy Groups`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
