version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Access Leaf Switch Profile Module

  Manages ACI Access Leaf Switch Profile

  Location in GUI:
  `Fabric` » `Access Policies` » `Switches` » `Leaf Switches` » `Profiles`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
