version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Geolocation Module

  ACI Geolocation

  Location in GUI:
  `Fabric` » `Fabric Policies` » `Policies` » `Geolocation`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
