version: '>= 0.14.0'

formatter: markdown table

content: |-
  #  Terraform ACI Tenant SPAN Source Group Module

  Manages ACI Tenant SPAN Source Group

  Location in GUI:
  `Tenants` » `Policies` » `Troubleshooting` » `SPAN` » `SPAN Source Groups`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
