version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Keyring Module

  Manages ACI Keyring

  Location in GUI:
  `Admin` » `AAA` » `Security` » `Public Key Management` » `Key Rings`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
