version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Syslog Policy Module

  Manages ACI Syslog Policy

  Location in GUI:
  `Admin` » `External Data Collectors` » `Monitoring Destinations` » `Syslog`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
